language: java

before_install:
  - ant init-ivy
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install: ant resolve
    
addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: required
